# Load Yahoo Financials Library

In [1]:
from yahoofinancials import YahooFinancials
import pandas as pd

# Load TOP40 Companies

In [40]:
tickers = pd.read_csv('../data/external/jse_top_40.csv')
tickers['Symbol'] +='.JO'
tickers.columns = ['Company_Name','URL_Description','Symbol','Sector']

,ari-tbl-col-0,ari-tbl-col-0 href,ari-tbl-col-1,ari-tbl-col-2
0,4Sight Holdings Limited,https://www.african-markets.com/en/stock-marke...,4SI,Financial Services
1,ABSA Bank Limited,https://www.african-markets.com/en/stock-marke...,ABSP,Banks
2,Accelerate Property Fund Limited,https://www.african-markets.com/en/stock-marke...,APF,Real Estate Investment Trusts
3,Accentuate Limited,https://www.african-markets.com/en/stock-marke...,ACE,Chemicals
4,Acsion Limited,https://www.african-markets.com/en/stock-marke...,ACS,Real Estate Investment & Services
5,Adapt It Holdings Limited,https://www.african-markets.com/en/stock-marke...,ADI,Software & Computer Services
6,Adcock Ingram Holdings Limited,https://www.african-markets.com/en/stock-marke...,AIP,Pharmaceuticals & Biotechnology
7,Adcorp Holdings Limited,https://www.african-markets.com/en/stock-marke...,ADR,Support Services
8,Adrenna Property Group Limited,https://www.african-markets.com/en/stock-marke...,ANA,Real Estate Investment & Services
9,Advanced Health Limited,https://www.african-markets.com/en/stock-marke...,AVL,Health Care Equipment & Services
10,Advtech Limited,https://www.african-markets.com/en/stock-marke...,ADH,General Retailers
11,AECI Limited,https://www.african-markets.com/en/stock-marke...,AFE,Chemicals
12,AEP Energy Africa Limited,https://www.african-markets.com/en/stock-marke...,AEY,Financial Services
13,African And Overseas Enterprises Limited,https://www.african-markets.com/en/stock-marke...,AOO,General Retailers
14,African Bank Investments Limited,https://www.african-markets.com/en/stock-marke...,ABL,Financial Services
15,African Dawn Capital Limited,https://www.african-markets.com/en/stock-marke...,ADW,Financial Services
16,African Eagle Resources Plc,https://www.african-markets.com/en/stock-marke...,AEA,Industrial Metals & Mining
17,African Equity Empowerment Investments Limited,https://www.african-markets.com/en/stock-marke...,AEE,Financial Services
18,African Media Entertainment Limited,https://www.african-markets.com/en/stock-marke...,AME,Media
19,African Oxygen Limited,https://www.african-markets.com/en/stock-marke...,AFX,Chemicals
20,African Rainbow Minerals Limited,https://www.african-markets.com/en/stock-marke...,ARI,Industrial Metals & Mining
21,Afrimat Limited,https://www.african-markets.com/en/stock-marke...,AFT,Construction & Materials
22,Afrocentric Investment Corp Limited,https://www.african-markets.com/en/stock-marke...,ACT,Financial Services
23,AH-Vest Limited,https://www.african-markets.com/en/stock-marke...,AHL,Food Producers
24,Alaris Holdings Limited,https://www.african-markets.com/en/stock-marke...,ALH,Aerospace & Defense
25,Alert Steel Holdings Limited,https://www.african-markets.com/en/stock-marke...,AET,General Retailers
26,Alexander Forbes Group Holdings Limited,https://www.african-markets.com/en/stock-marke...,AFH,Financial Services
27,Allied Electronics Corporation Limited,https://www.african-markets.com/en/stock-marke...,AEL,Software & Computer Services
28,Alviva Holdings Limited,https://www.african-markets.com/en/stock-marke...,PNC,Technology Hardware & Equipment
29,Amalgamated Electronic Corp Limited,https://www.african-markets.com/en/stock-marke...,AER,Electronic & Electrical Equipment
...,...,...,...,...
382,Trans Hex Group Limited,https://www.african-markets.com/en/stock-marke...,TSX,Mining
383,Transaction Capital Limited,https://www.african-markets.com/en/stock-marke...,TCP,Financial Services
384,Transpaco Limited,https://www.african-markets.com/en/stock-marke...,TPC,General Industrials
385,Trellidor Holdings Limited,https://www.african-markets.com/en/stock-marke...,TRL,Construction & Materials
386,Trematon Capital Investments Ltd,https://www.african-markets.com/en/stock-marke...,TMT,Financial Services
387,Trencor Limited,https://www.african-markets.com/en/stock-marke...,TRE,Industrial Transportation
388,Trustco Group Holdings Limited,https://www.african-markets.com/en/stock-marke...,TTO,Financial Services
389,Truworths International Limited,https://www.african-markets.com/en/stock-marke...,TRU,General Retailers
390,Tsogo Sun Holdings Limited,https://www.african-markets.com/en/stock-marke...,TSH,Travel & Leisure
391,Universal Partners Limited,https://www.african-markets.com/en/stock-marke...,UPL,Financial Services
392,Value Group Limited,https://www.african-markets.com/en/stock-marke...,VLE,Travel & Leisure
393,Verimark Holdings Limited,https://www.african-markets.com/en/stock-marke...,VMK,General Retailers
394,VestIN Holdings Limited,https://www.african-markets.com/en/stock-marke...,VIN,Financial Services
395,Visual International Holdings Limited,https://www.african-markets.com/en/stock-marke...,VIS,Real Estate Investment & Services
396,Vivo Energy Plc,https://www.african-markets.com/en/stock-marke...,VVO,Oil & Gas Producers
397,Vodacom Group Limited,https://www.african-markets.com/en/stock-marke...,VOD,Mobile Telecommunications
398,Vukile Property Fund Limited,https://www.african-markets.com/en/stock-marke...,VKE,Real Estate Investment Trusts
399,Vunani Limited,https://www.african-markets.com/en/stock-marke...,VUN,Financial Services
400,W G Wearne Limited,https://www.african-markets.com/en/stock-marke...,WEA,Construction & Materials
401,Wescoal Holdings Limited,https://www.african-markets.com/en/stock-marke...,WSL,Support Services
402,Wesizwe Platinum Limited,https://www.african-markets.com/en/stock-marke...,WEZ,Mining
403,Wilderness Holdings Limited,https://www.african-markets.com/en/stock-marke...,WIL,Travel & Leisure
404,William Tell Holdings Limited,https://www.african-markets.com/en/stock-marke...,WTL,Forestry & Paper
405,Wilson Bayly Holmes-Ovcon Limited,https://www.african-markets.com/en/stock-marke...,WBO,Construction & Materials
406,Winhold Limited,https://www.african-markets.com/en/stock-marke...,WNH,General Industrials
407,Woolworths Holdings Limited,https://www.african-markets.com/en/stock-marke...,WHL,General Retailers
408,Workforce Holdings Limited,https://www.african-markets.com/en/stock-marke...,WKF,Support Services
409,York Timber Holdings Limited,https://www.african-markets.com/en/stock-marke...,YRK,Forestry & Paper
410,ZCI Limited,https://www.african-markets.com/en/stock-marke...,ZCI,Industrial Metals & Mining
411,Zeder Investments Limited,https://www.african-markets.com/en/stock-marke...,ZED,Financial Services

# Annual Cash Statement History

In [21]:
companies = pd.DataFrame()
for i in range(len(tickers)):
        symbol = tickers.iloc[i]['Symbol']
        
        symbol = symbol
        
        try:
            df = pd.DataFrame()
            data = []
            [data.append(pd.DataFrame.from_dict(i).T) for i in YahooFinancials(symbol).get_financial_stmts('annual', 'cash')['cashflowStatementHistory'][symbol]]
    
            for i in data:
                df = pd.concat([df,i])
                
            df['Ticker'] = symbol
            
            companies = pd.concat([companies, df])
        except:
            pass

companies['Date'] = pd.to_datetime(companies.index)
companies        
        
companies.head()

C:\Users\Naeem Asvat\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  del sys.path[0]
C:\Users\Naeem Asvat\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,Ticker,capitalExpenditures,changeInCash,changeToAccountReceivables,changeToInventory,changeToLiabilities,changeToNetincome,changeToOperatingActivities,depreciation,dividendsPaid,effectOfExchangeRate,investments,netBorrowings,netIncome,otherCashflowsFromFinancingActivities,otherCashflowsFromInvestingActivities,totalCashFromFinancingActivities,totalCashFromOperatingActivities,totalCashflowsFromInvestingActivities
2017-12-31,4SI.JO,-8.120400e+04,8.436536e+06,NaN,NaN,0.0,-9.600108e+06,NaN,1.066636e+06,NaN,110606.0,8020044.0,4715012.0,3.664088e+06,-6.594500e+06,NaN,4.094580e+05,-4.869384e+06,1.278586e+07
2016-12-31,4SI.JO,-1.888990e+05,-1.935875e+06,4547089.0,NaN,-805769.0,-1.190540e+05,NaN,1.444530e+05,NaN,-301055.0,8020044.0,-5166.0,-5.149415e+06,-6.594500e+06,-49624.0,-5.166000e+03,-5.766130e+05,-1.053041e+06
2015-12-31,4SI.JO,-1.299510e+05,4.433855e+06,7292248.0,NaN,-5299750.0,7.640580e+05,NaN,7.101300e+04,NaN,27614.0,-47177.0,577180.0,4.002790e+06,-6.594500e+06,-49624.0,5.771800e+05,7.530816e+06,-3.681755e+06
2014-12-31,4SI.JO,-5.612100e+04,7.055510e+05,-11155462.0,NaN,9013898.0,-4.622700e+04,NaN,3.121700e+04,-1.300000e+05,-22953.0,-47177.0,577180.0,2.470151e+06,-6.594500e+06,-49624.0,-1.300000e+05,1.573997e+06,-7.154930e+05
2017-12-31,ABSP.JO,-2.622000e+09,-1.376000e+09,NaN,NaN,0.0,3.170000e+09,-2.000900e+10,1.587000e+09,-6.510000e+09,NaN,NaN,36000000.0,8.477000e+09,3.045000e+10,675000000.0,3.745800e+10,-3.492800e+10,-3.906000e+09

In [29]:
companies = pd.DataFrame()
for i in range(len(tickers)):
        symbol = tickers.iloc[i]['Symbol']
        
        symbol = symbol
        
        try:
            df = pd.DataFrame()
            data = []
            [data.append(pd.DataFrame.from_dict(i).T) for i in YahooFinancials(symbol).get_financial_stmts('annual', 'cash')['cashflowStatementHistory'][symbol]]
    
            for i in data:
                df = pd.concat([df,i])
                
            df['Ticker'] = symbol
            
            companies = pd.concat([companies, df])
        except:
            pass

companies['Date'] = pd.to_datetime(companies.index)

companies = companies.reset_index()    

companies.to_csv('../data/raw/TOP40_Cash_Annual.csv', index=False)

companies.head()

C:\Users\Naeem Asvat\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  del sys.path[0]
C:\Users\Naeem Asvat\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,Ticker,capitalExpenditures,changeInCash,changeToAccountReceivables,changeToInventory,changeToLiabilities,changeToNetincome,changeToOperatingActivities,depreciation,dividendsPaid,effectOfExchangeRate,investments,netBorrowings,netIncome,otherCashflowsFromFinancingActivities,otherCashflowsFromInvestingActivities,totalCashFromFinancingActivities,totalCashFromOperatingActivities,totalCashflowsFromInvestingActivities,Date
2017-12-31,4SI.JO,-8.120400e+04,8.436536e+06,NaN,NaN,0.0,-9.600108e+06,NaN,1.066636e+06,NaN,110606.0,8020044.0,4715012.0,3.664088e+06,-6.594500e+06,NaN,4.094580e+05,-4.869384e+06,1.278586e+07,2017-12-31
2016-12-31,4SI.JO,-1.888990e+05,-1.935875e+06,4547089.0,NaN,-805769.0,-1.190540e+05,NaN,1.444530e+05,NaN,-301055.0,8020044.0,-5166.0,-5.149415e+06,-6.594500e+06,-49624.0,-5.166000e+03,-5.766130e+05,-1.053041e+06,2016-12-31
2015-12-31,4SI.JO,-1.299510e+05,4.433855e+06,7292248.0,NaN,-5299750.0,7.640580e+05,NaN,7.101300e+04,NaN,27614.0,-47177.0,577180.0,4.002790e+06,-6.594500e+06,-49624.0,5.771800e+05,7.530816e+06,-3.681755e+06,2015-12-31
2014-12-31,4SI.JO,-5.612100e+04,7.055510e+05,-11155462.0,NaN,9013898.0,-4.622700e+04,NaN,3.121700e+04,-1.300000e+05,-22953.0,-47177.0,577180.0,2.470151e+06,-6.594500e+06,-49624.0,-1.300000e+05,1.573997e+06,-7.154930e+05,2014-12-31
2017-12-31,ABSP.JO,-2.622000e+09,-1.376000e+09,NaN,NaN,0.0,3.170000e+09,-2.000900e+10,1.587000e+09,-6.510000e+09,NaN,NaN,36000000.0,8.477000e+09,3.045000e+10,675000000.0,3.745800e+10,-3.492800e+10,-3.906000e+09,2017-12-31

# Annual Balance Sheet Statement History

In [30]:
companies = pd.DataFrame()
for i in range(len(tickers)):
        symbol = tickers.iloc[i]['Symbol']
        
        symbol = symbol
        
        try:
            df = pd.DataFrame()
            data = []
            [data.append(pd.DataFrame.from_dict(i).T) for i in YahooFinancials(symbol).get_financial_stmts('annual', 'balance')['balanceSheetHistory'][symbol]]
    
            for i in data:
                df = pd.concat([df,i])
                
            df['Ticker'] = symbol
            
            companies = pd.concat([companies, df])
        except:
            pass

companies['Date'] = pd.to_datetime(companies.index)

balance = companies.copy()

balance = balance.reset_index()    

balance.to_csv('../data/raw/TOP40_Balance_Annual.csv', index=False)

balance.head()

C:\Users\Naeem Asvat\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  del sys.path[0]
C:\Users\Naeem Asvat\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,Ticker,accountsPayable,capitalSurplus,cash,commonStock,deferredLongTermAssetCharges,deferredLongTermLiab,goodWill,intangibleAssets,inventory,...,retainedEarnings,shortLongTermDebt,shortTermInvestments,totalAssets,totalCurrentAssets,totalCurrentLiabilities,totalLiab,totalStockholderEquity,treasuryStock,Date
2017-12-31,4SI.JO,5.460147e+06,NaN,4.462558e+06,41295921.0,1169489.0,NaN,23803478.0,1.048784e+07,144862.0,...,1.832044e+06,3.964450e+06,NaN,5.346146e+07,1.495210e+07,8.814140e+06,1.338118e+07,4.016782e+07,-2.960141e+06,2017-12-31
2016-12-31,4SI.JO,2.575558e+06,NaN,7.178584e+06,10000.0,607566.0,NaN,1988528.0,1.641390e+06,NaN,...,8.461554e+06,5.520140e+05,4.708200e+04,1.866767e+07,1.174023e+07,5.355483e+06,7.339098e+06,7.906308e+06,-5.652460e+05,2016-12-31
2015-12-31,4SI.JO,2.496693e+06,NaN,9.114459e+06,10000.0,340559.0,NaN,1988528.0,1.520288e+06,NaN,...,1.359531e+07,5.571800e+05,NaN,2.452420e+07,1.828974e+07,5.371763e+06,8.250012e+06,1.295436e+07,-6.509470e+05,2015-12-31
2014-12-31,4SI.JO,6.664742e+06,NaN,4.680604e+06,10000.0,800.0,NaN,NaN,9.838670e+05,NaN,...,9.592521e+06,NaN,1.996700e+04,2.248061e+07,2.104527e+07,9.209298e+06,1.287338e+07,9.602521e+06,NaN,2014-12-31
2017-12-31,ABSP.JO,6.279440e+11,3.687900e+10,1.104000e+10,304000000.0,51000000.0,162000000.0,112000000.0,3.749000e+09,14000000.0,...,3.785500e+10,2.366090e+11,3.459500e+10,9.883580e+11,1.829270e+11,7.966380e+11,9.030290e+11,8.068300e+10,5.645000e+09,2017-12-31

# Annual Income Statement History

In [31]:
companies = pd.DataFrame()
for i in range(len(tickers)):
        symbol = tickers.iloc[i]['ari-tbl-col-1']
        
        symbol = symbol+'.JO'
        
        try:
            df = pd.DataFrame()
            data = []
            [data.append(pd.DataFrame.from_dict(i).T) for i in YahooFinancials(symbol).get_financial_stmts('annual', 'income')['incomeStatementHistory'][symbol]]
    
            for i in data:
                df = pd.concat([df,i])
                
            df['Ticker'] = symbol
            
            companies = pd.concat([companies, df])
        except:
            pass

companies['Date'] = pd.to_datetime(companies.index)

income = companies.copy()
        
income = income.reset_index()    

income.to_csv('../data/raw/TOP40_Income_Annual.csv', index=False)
    
income.head()

C:\Users\Naeem Asvat\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

,Ticker,costOfRevenue,discontinuedOperations,ebit,effectOfAccountingCharges,extraordinaryItems,grossProfit,incomeBeforeTax,incomeTaxExpense,interestExpense,...,nonRecurring,operatingIncome,otherItems,otherOperatingExpenses,researchDevelopment,sellingGeneralAdministrative,totalOperatingExpenses,totalOtherIncomeExpenseNet,totalRevenue,Date
2017-12-31,4SI.JO,5164250.0,NaN,4707890.0,NaN,NaN,1.879759e+07,4.624124e+06,4.398360e+05,-127192.0,...,NaN,4.707890e+06,NaN,-1.383900e+05,NaN,1.422809e+07,1.925395e+07,-83766.0,2.396184e+07,2017-12-31
2016-12-31,4SI.JO,1324195.0,NaN,-4413615.0,NaN,NaN,9.069180e+06,-4.813063e+06,7.336230e+05,-127192.0,...,NaN,-4.413615e+06,NaN,-2.639000e+03,NaN,1.348543e+07,1.480699e+07,-399448.0,1.039338e+07,2016-12-31
2015-12-31,4SI.JO,4914919.0,NaN,4650420.0,NaN,NaN,1.355445e+07,4.781021e+06,1.192909e+06,-127192.0,...,NaN,4.650420e+06,NaN,-1.494950e+05,NaN,9.053529e+06,1.381895e+07,130601.0,1.846937e+07,2015-12-31
2014-12-31,4SI.JO,7622527.0,NaN,3012722.0,NaN,NaN,1.041051e+07,2.818674e+06,3.507640e+05,-127192.0,...,NaN,3.012722e+06,NaN,-1.494950e+05,NaN,7.397786e+06,1.502031e+07,-194048.0,1.803304e+07,2014-12-31
2017-12-31,ABSP.JO,136000000.0,NaN,0.0,NaN,NaN,4.480800e+10,1.175500e+10,3.278000e+09,NaN,...,NaN,1.209000e+10,NaN,2.990900e+10,NaN,2.809000e+09,3.285400e+10,-335000000.0,4.494400e+10,2017-12-31

In [46]:
tickers = pd.read_csv('../data/external/jse_top_40.csv')

tickers.columns = ['Company_Name','URL_Description','Symbol','Sector']

tickers = tickers.drop(columns='URL_Description')

tickers.to_csv('../data/raw/TOP40_Companies.csv',index=False)

# Download Historical Stock Price

In [80]:
daily_bank_stock_prices = []
#[daily_bank_stock_prices.append(YahooFinancials(i).get_historical_price_data('2008-01-01', '2019-04-20', 'weekly')) for i in tickers.Symbol.unique()]

for i in tickers.Symbol.unique():
    
    try:
        daily_bank_stock_prices.append(YahooFinancials(i).get_historical_price_data('2008-01-01', '2019-04-20', 'weekly'))

    except:
        print('Could not find:',i)
        pass

Could not find: ABL.JO
Could not find: AEA.JO
Could not find: AHL.JO
Could not find: AET.JO
Could not find: PNC.JO
Could not find: AER.JO
Could not find: ANB.JO
Could not find: ANS.JO
Could not find: AIA.JO
Could not find: APK.JO
Could not find: AVR.JO
Could not find: AWT.JO
Could not find: BGA.JO
Could not find: BSR.JO
Could not find: BEG.JO
Could not find: BIL.JO
Could not find: BK1P.JO
Could not find: BFS.JO
Could not find: BNT.JO
Could not find: BAT.ZA.JO
Could not find: BIK.JO
Could not find: BSS.JO
Could not find: BDM.JO
Could not find: CAC.JO
Could not find: CVH.JO
Could not find: CRG.JO
Could not find: CVW.JO
Could not find: CRD.JO
Could not find: CSP.JO
Could not find: CHP.JO
Could not find: CMA.JO
Could not find: CUL.JO
Could not find: DCT.JO
Could not find: DRN.JO
Could not find: DMC.JO
Could not find: DST.JO
Could not find: EPP.JO
Could not find: ECS.JO
Could not find: EFG.JO
Could not find: EEL.JO
Could not find: ELR.JO
Could not find: ELI.JO
Could not find: EMI.JO
Could not find: ENX.JO
Could not find: EOH.JO
Could not find: EPE.JO
Could not find: EQS.JO
Could not find: EQU.JO
Could not find: ERN.JO
Could not find: ESR.JO
Could not find: MAS.JO
Could not find: EHS.JO
Could not find: EXP.JO
Could not find: EXX.JO
Could not find: FVT.JO
Could not find: FBR.JO
Could not find: FCR.JO
Could not find: FGL.JO
Could not find: FSE.JO
Could not find: FSR.JO
Could not find: FFB.JO
Could not find: FDP.JO
Could not find: GAI.JO
Could not find: GIY.JO
Could not find: GLN.JO
Could not find: GAM.JO
Could not find: GTC.JO
Could not find: GLI.JO
Could not find: GBI.JO
Could not find: GFI.JO
Could not find: GDN.JO
Could not find: GPL.JO
Could not find: GBG.JO
Could not find: GND.JO
Could not find: GSH.JO
Could not find: GTR.JO
Could not find: GRF.JO
Could not find: GRT.JO
Could not find: HAR.JO
Could not find: HET.JO
Could not find: HSP.JO
Could not find: HIL.JO
Could not find: HCI.JO
Could not find: HPR.JO
Could not find: HPA.JO
Could not find: HWN.JO
Could not find: HDC.JO
Could not find: HUG.JO
Could not find: HLM.JO
Could not find: HUL.JO
Could not find: HWA.JO
Could not find: HYP.JO
Could not find: ILE.JO
Could not find: IMP.JO
Could not find: IPL.JO
Could not find: IDQ.JO
Could not find: ILU.JO
Could not find: ING.JO
Could not find: ISB.JO
Could not find: IHL.JO
Could not find: IWE.JO
Could not find: ITU.JO
Could not find: IAP.JO
Could not find: INL.JO
Could not find: INP.JO
Could not find: IPF.JO
Could not find: IVT.JO
Could not find: IPS.JO
Could not find: ISA.JO
Could not find: ITE.JO
Could not find: JSC.JO
Could not find: JSE.JO
Could not find: JBL.JO
Could not find: KAL.JO
Could not find: KAP.JO
Could not find: KDV.JO
Could not find: KEH.JO
Could not find: KBO.JO
Could not find: KP2.JO
Could not find: KIO.JO
Could not find: LAB.JO
Could not find: LEW.JO
Could not find: GRP.JO
Could not find: LDO.JO
Could not find: MFI.JO
Could not find: MLD.JO
Could not find: MAP.JO
Could not find: CZA.JO
Could not find: MMG.JO
Could not find: MRI.JO
Could not find: MMH.JO
Could not find: MNY.JO
Could not find: MCG.JO
Could not find: MUR.ZA.JO
Could not find: NEP.JO
Could not find: ORL.JO
Could not find: OMU.za.JO
Could not find: OML.JO
Could not find: PGL.JO
Could not find: PET.JO
Could not find: PWK.JO
Could not find: PLL.JO
Could not find: PFF.JO
Could not find: PCT.JO
Could not find: PKH.JO
Could not find: QPG.JO
Could not find: RAR.JO
Could not find: RBA.JO
Could not find: REI.JO
Could not find: ROC.JO
Could not find: RDI.JO
Could not find: SAB.JO
Could not find: SCV.JO
Could not find: SNU.JO
Could not find: SAH.JO
Could not find: SOV.JO
Could not find: SRR.JO
Could not find: SHF.JO
Could not find: STA.JO
Could not find: SGA.JO
Could not find: TAW.JO
Could not find: PIV.JO
Could not find: WCC.JO
Could not find: TCS.JO
Could not find: VIN.JO
Could not find: WTL.JO
Could not find: WNH.JO
Could not find: ZCI.JO

# Format JSON to CSV

In [128]:
prices=pd.DataFrame()

for i in daily_bank_stock_prices:
    for j in i.keys():
            try:
                #print(j)
                temp = pd.DataFrame.from_dict(i[j]['prices'])
                temp['Symbol']=j
                prices=pd.concat([prices,temp])
            except:
                pass

prices.head()

prices.to_csv('../data/raw/TOP40_Historical_Sales.csv',index=False)

4SI.JO
ABSP.JO
APF.JO
ACE.JO
ACS.JO
ADI.JO
AIP.JO
ADR.JO
ANA.JO
AVL.JO
ADH.JO
AFE.JO
AEY.JO
AOO.JO
ADW.JO
AEE.JO
AME.JO
AFX.JO
ARI.JO
AFT.JO
ACT.JO

C:\Users\Naeem Asvat\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  if __name__ == '__main__':

ALH.JO
AFH.JO
AEL.JO
ACG.JO
AND.JO
AMS.JO
AGL.JO
ANG.JO
ARH.JO
ACL.JO
ART.JO
AWA.JO
ASC.JO
APN.JO
ASR.JO
ARA.JO
ARL.JO
ALP.JO
ATL.JO
ATT.JO
AEG.JO
AVI.JO
AYO.JO
BWN.JO
BAW.JO
BAU.JO
BEL.JO
BID.JO
BLU.JO
BCF.JO
BWZ.JO
BRT.JO
BTI.JO
BUC.JO
CGR.JO
CCO.JO
CRP.JO
CTA.JO
CPI.JO
CTK.JO
CSB.JO
CAT.JO
CMO.JO
CLH.JO
CLS.JO
CLI.JO
CLR.JO
CGN.JO
COM.JO
CMH.JO
CFR.JO
CND.JO
CIL.JO
CML.JO
CKS.JO
CSG.JO
COH.JO
DTC.JO
DTA.JO
DLT.JO
DNB.JO
DIA.JO
DCP.JO
DSY.JO
DAW.JO
DRD.JO
EMH.JO
EPS.JO
LBH.JO
L2D.JO
LBR.JO
LHC.JO
LNF.JO
L4L.JO
LON.JO
MMP.JO
MSP.JO
MSM.JO
MDI.JO
MZR.JO
MEI.JO
MRF.JO
MTA.JO
MFL.JO
MLE.JO
MED.JO
MIX.JO
MMI.JO
MND.JO
MNP.JO
MNK.JO
MTH.JO
MPT.JO
MRP.JO
MTN.JO
MST.JO
NPK.JO
NPN.JO
NED.JO
NT1.JO
NTC.JO
NFP.JO
NRL.JO
NCS.JO
NIV.JO
NHM.JO
NVS.JO
NWL.JO
NUT.JO
NVE.JO
OAO.JO
OAS.JO
OCE.JO
OCT.JO
OMN.JO
OLG.JO
ORN.JO
ORE.JO
PAN.JO
PEM.JO
PGR.JO
PHM.JO
PIK.JO
PFG.JO
PPC.JO
PMV.JO
PSG.JO
KST.JO
PSV.JO
PPE.JO
PPR.JO
QFH.JO
QLT.JO
RMI.JO
RNG.JO
RBX.JO
RAV.JO
RCL.JO
RPL.JO
REB.JO
RACP.JO
RDF.JO
REM.JO
REN.JO
RES.JO
RSG.JO
RLO.JO
RTO.JO
RHB.JO
RFG.JO
RMH.JO
RLF.JO
RBP.JO
SAC.JO
SBV.JO
SAR.JO
SLM.JO
SNT.JO
SNV.JO
SAP.JO
SFN.JO
SOL.JO
SCD.JO
SEP.JO
SHP.JO
SGL.JO
SVB.JO
SRE.JO
SOH.JO
S32.JO
SPA.JO
SEA.JO
SUR.JO
SDO.JO
SBK.JO
SSK.JO
SNH.JO
SCP.JO
STP.JO
SSS.JO
SUI.JO
SPG.JO
SYG.JO
TAS.JO
TLM.JO
TKG.JO
TEX.JO
THA.JO
BVT.JO
TFG.JO
SPP.JO
TBS.JO
TBG.JO
TON.JO
TOR.JO
TWR.JO
TDH.JO
TSX.JO
TCP.JO
TPC.JO
TRL.JO
TMT.JO
TRE.JO
TTO.JO
TRU.JO
TSH.JO
UPL.JO
VLE.JO
VMK.JO
VIS.JO
VVO.JO
VOD.JO
VKE.JO
VUN.JO
WEA.JO
WSL.JO
WEZ.JO
WIL.JO
WBO.JO
WHL.JO
WKF.JO
YRK.JO
ZED.JO

,Symbol,adjclose,close,date,formatted_date,high,low,open,volume
0,4SI.JO,250.0,250.0,1.508105e+09,2017-10-15,280.0,205.0,205.0,624057.0
1,4SI.JO,255.0,255.0,1.508710e+09,2017-10-22,290.0,243.0,250.0,957751.0
2,4SI.JO,251.0,251.0,1.509314e+09,2017-10-29,270.0,236.0,260.0,307565.0
3,4SI.JO,209.0,209.0,1.509919e+09,2017-11-05,251.0,180.0,251.0,254905.0
4,4SI.JO,203.0,203.0,1.510524e+09,2017-11-12,250.0,180.0,210.0,166669.0

In [134]:
prices['date'] = pd.to_datetime(prices['date'])

prices['date'] = prices['formatted_date']

In [135]:
prices

,Symbol,adjclose,close,date,formatted_date,high,low,open,volume
0,4SI.JO,250.00,250.00,2017-10-15,2017-10-15,280.0,205.00,205.00,624057.0
1,4SI.JO,255.00,255.00,2017-10-22,2017-10-22,290.0,243.00,250.00,957751.0
2,4SI.JO,251.00,251.00,2017-10-29,2017-10-29,270.0,236.00,260.00,307565.0
3,4SI.JO,209.00,209.00,2017-11-05,2017-11-05,251.0,180.00,251.00,254905.0
4,4SI.JO,203.00,203.00,2017-11-12,2017-11-12,250.0,180.00,210.00,166669.0
5,4SI.JO,204.00,204.00,2017-11-19,2017-11-19,220.0,173.00,205.00,106092.0
6,4SI.JO,202.00,202.00,2017-11-26,2017-11-26,205.0,179.00,200.00,47150.0
7,4SI.JO,189.00,189.00,2017-12-03,2017-12-03,200.0,181.00,181.00,30032.0
8,4SI.JO,190.00,190.00,2017-12-10,2017-12-10,199.0,160.00,199.00,124339.0
9,4SI.JO,179.00,179.00,2017-12-17,2017-12-17,198.0,156.00,198.00,32617.0
10,4SI.JO,170.00,170.00,2017-12-24,2017-12-24,180.0,1.79,1.79,2040.0
11,4SI.JO,174.00,174.00,2017-12-31,2017-12-31,185.0,1.70,1.70,170144.0
12,4SI.JO,163.00,163.00,2018-01-07,2018-01-07,185.0,145.00,185.00,193278.0
13,4SI.JO,195.00,195.00,2018-01-14,2018-01-14,195.0,150.00,161.00,313182.0
14,4SI.JO,193.00,193.00,2018-01-21,2018-01-21,200.0,156.00,190.00,328979.0
15,4SI.JO,166.00,166.00,2018-01-28,2018-01-28,199.0,157.00,199.00,76406.0
16,4SI.JO,160.00,160.00,2018-02-04,2018-02-04,189.0,150.00,165.00,142721.0
17,4SI.JO,154.00,154.00,2018-02-11,2018-02-11,170.0,145.00,160.00,135232.0
18,4SI.JO,149.00,149.00,2018-02-18,2018-02-18,154.0,118.00,154.00,107128.0
19,4SI.JO,130.00,130.00,2018-02-25,2018-02-25,136.0,120.00,130.00,366397.0
20,4SI.JO,155.00,155.00,2018-03-04,2018-03-04,155.0,85.00,130.00,341373.0
21,4SI.JO,140.00,140.00,2018-03-11,2018-03-11,146.0,109.00,146.00,312675.0
22,4SI.JO,140.00,140.00,2018-03-18,2018-03-18,140.0,1.28,125.00,107138.0
23,4SI.JO,1.40,1.40,2018-03-25,2018-03-25,140.0,1.40,140.00,141180.0
24,4SI.JO,130.00,130.00,2018-04-01,2018-04-01,140.0,1.40,1.40,65958.0
25,4SI.JO,145.00,145.00,2018-04-08,2018-04-08,145.0,101.00,130.00,127752.0
26,4SI.JO,145.00,145.00,2018-04-15,2018-04-15,145.0,125.00,140.00,163759.0
27,4SI.JO,1.43,1.43,2018-04-22,2018-04-22,145.0,1.43,145.00,142972.0
28,4SI.JO,121.00,121.00,2018-04-29,2018-04-29,144.0,1.39,143.00,130351.0
29,4SI.JO,139.00,139.00,2018-05-06,2018-05-06,143.0,120.00,122.00,76155.0
...,...,...,...,...,...,...,...,...,...
559,ZED.JO,470.00,470.00,2018-09-17,2018-09-17,499.0,461.00,469.00,5518212.0
560,ZED.JO,476.00,476.00,2018-09-24,2018-09-24,494.0,450.00,494.00,6163908.0
561,ZED.JO,461.00,461.00,2018-10-01,2018-10-01,500.0,450.00,475.00,16651115.0
562,ZED.JO,461.00,461.00,2018-10-08,2018-10-08,480.0,441.00,460.00,6735995.0
563,ZED.JO,479.00,479.00,2018-10-15,2018-10-15,482.0,460.00,475.00,5581575.0
564,ZED.JO,470.00,470.00,2018-10-22,2018-10-22,482.0,456.00,479.00,40774745.0
565,ZED.JO,474.00,474.00,2018-10-29,2018-10-29,487.0,458.00,458.00,1922773.0
566,ZED.JO,456.00,456.00,2018-11-05,2018-11-05,477.0,455.00,474.00,8031768.0
567,ZED.JO,470.00,470.00,2018-11-12,2018-11-12,475.0,431.00,455.00,2113856.0
568,ZED.JO,469.00,469.00,2018-11-19,2018-11-19,475.0,456.00,470.00,5032306.0
569,ZED.JO,473.00,473.00,2018-11-26,2018-11-26,474.0,456.00,456.00,5346407.0
570,ZED.JO,478.00,478.00,2018-12-03,2018-12-03,501.0,471.00,471.00,7309729.0
571,ZED.JO,490.00,490.00,2018-12-10,2018-12-10,510.0,470.00,490.00,6012023.0
572,ZED.JO,470.00,470.00,2018-12-17,2018-12-17,500.0,466.00,500.00,10997462.0
573,ZED.JO,447.00,447.00,2018-12-24,2018-12-24,474.0,434.00,470.00,3685236.0
574,ZED.JO,460.00,460.00,2018-12-31,2018-12-31,470.0,436.00,447.00,2571230.0
575,ZED.JO,455.00,455.00,2019-01-07,2019-01-07,476.0,440.00,451.00,4441605.0
576,ZED.JO,455.00,455.00,2019-01-14,2019-01-14,468.0,443.00,445.00,1631389.0
577,ZED.JO,454.00,454.00,2019-01-21,2019-01-21,464.0,447.00,456.00,2288908.0
578,ZED.JO,441.00,441.00,2019-01-28,2019-01-28,455.0,435.00,450.00,3199745.0
579,ZED.JO,441.00,441.00,2019-02-04,2019-02-04,451.0,435.00,441.00,3080770.0
580,ZED.JO,427.00,427.00,2019-02-11,2019-02-11,444.0,419.00,441.00,2922717.0
581,ZED.JO,423.00,423.00,2019-02-18,2019-02-18,438.0,400.00,426.00,3931542.0
582,ZED.JO,425.00,425.00,2019-02-25,2019-02-25,438.0,410.00,416.00,3607805.0
583,ZED.JO,415.00,415.00,2019-03-04,2019-03-04,430.0,404.00,425.00,3570671.0
584,ZED.JO,430.00,430.00,2019-03-11,2019-03-11,441.0,397.00,416.00,6137330.0
585,ZED.JO,408.00,408.00,2019-03-18,2019-03-18,443.0,407.00,435.00,6119545.0
586,ZED.JO,416.00,416.00,2019-03-25,2019-03-25,416.0,401.00,408.00,2012767.0
587,ZED.JO,412.00,412.00,2019-04-01,2019-04-01,418.0,408.00,414.00,831220.0
588,ZED.JO,420.00,420.00,2019-04-04,2019-04-04,420.0,405.00,405.00,111352.0